extends Node3D
## THE ZONE ROOT of a generated world — the same contract every zone in this game keeps: it is
## in group "zone", it stands at a known place, and `World.go_to` finds a `SpawnA` marker in it.
##
## IT BUILDS ALMOST NOTHING. A world is GENERATED by one step and ASSEMBLED INTO A SCENE by
## another, and both of those happen long before anybody presses play: the ground, the spawn,
## the portal home and — in the scene you open — every building are NODES IN THE FILE. What is
## left for `_ready` is the one thing a file cannot carry: a Terrain3D comes back from a packed
## scene on the extension's own default collision mode, whatever it was saved with, so it has
## to be told again what walkable means. The rest of this script is fallbacks, and each of them
## says so when it fires, because a fallback firing means a scene was not written properly.
##
## THE GROUND. The streets of a generated city carry no floor of their own (see the city
## recipe), so something has to be walkable between them: a Terrain3D grown from the same map —
## flat under the walls, mountains around it, water in the ring — or, when the extension is not
## installed, the flat collider this zone had before. Nothing else here changes either way.
##
## THE BUILDINGS are streamed by Open World Database from the `.owdb` beside this scene: one
## unit of the generator's own — a block, a ward — per entry. This node does three things the
## addon cannot do for itself, and `world_stream.gd` says why each of them is not optional.

const Terrain := preload("res://scripts/world/world_terrain.gd")
const Stream := preload("res://scripts/world/world_stream.gd")

## The look a carved zone is entered under. `DungeonEnv` is the crypt's own — it snapshots every
## property it is about to write and plays the recording back on the way out — and the theme is
## the one the hand-built crypt uses, so a generated dungeon and an authored one are the same
## darkness rather than two people's idea of dark.
const CRYPT_THEME := "res://scenes/dungeon/themes/crypt.tres"

@export var map: WorldMap
## Where this zone parks. A GENERATED WORLD STANDS AT THE ORIGIN, unlike the hub-sized zones
## that park clear of one another: Terrain3D holds its regions in global space and ignores the
## transform of the node it hangs under, so a parked world would leave its ground behind. The
## export stays for a world with no terrain (the flat collider follows the node as it should).
@export var park := Vector3.ZERO
@export var ground_colour := Color(0.44, 0.42, 0.36)
## Off = the flat collider even where Terrain3D is installed (a screenshot, a test).
@export var terrain := true
## The world's own streaming manifest. EMPTY = the one named after this scene, beside it.
@export_file("*.owdb") var manifest := ""
## Off = keep the world's own daylight even underground (a screenshot, a look-dev pass). On, and
## carved, is what blacks the sky out; see `_underground`.
@export var underground := true

var stream: Node = null
var focus: Node3D = null
## Everything `DungeonEnv` took from the persistent outdoor Environment, to hand back intact.
## Empty = this zone is not currently holding the world.
var _env_snap := {}


func _ready() -> void:
	position = park
	stream = get_node_or_null("OWDB")
	focus = get_node_or_null("Focus")
	if map == null:
		push_warning("[World] no map: nothing to stand up")
		return
	# the ground is usually already here: it was generated with the world and saved into this
	# scene. Only a zone that has none grows one, and only a zone with no extension gets a slab.
	var carved := bool((map.site as Dictionary).get("carved", false))
	var ground: Node3D = get_node_or_null("Terrain")
	if ground == null and terrain and not carved:
		ground = Terrain.build(map, self)
	if ground == null and not carved:
		_ground()
	elif ground == null:
		# nothing to stand on but the rooms themselves, which is what carved means. The flat
		# fallback would put a plane back at y = 0 under every floor slab.
		pass
	else:
		# a terrain that came out of the packed scene comes back on the extension's DEFAULT
		# collision mode, whatever it was saved with: it is told again, out loud, what walkable
		# means (see world_terrain.stand_on) or the player falls through the streets
		Terrain.stand_on(ground)
		# the clipmap's rings — and, if it is ever put on dynamic collision, its shape window —
		# are centred on a camera the extension is TOLD about; without this it centres on
		# whatever it can find for itself, which in a scene that has not started is nothing
		Terrain.follow(ground, _camera())
		if not position.is_equal_approx(Vector3.ZERO):
			push_warning("[World] the terrain is in global space: a zone parked at %s stands beside its own ground" % str(position))
	var up := 0
	if stream != null and _units_on_disk():
		if focus != null:
			focus.set("home", map.spawn)
		Stream.attach(stream, _manifest())
		up = Stream.warm(stream, focus)
	if get_node_or_null("SpawnA") == null:
		push_warning("[World] %s has no SpawnA: the scene step writes one, so this scene was not written by it" % map.name)
	if carved and underground:
		_underground(true)
	var here := get_child_count()
	print("[World] %s: %d nodes in the scene, %d units streamed, %d cells, spawn %s" % [
			map.name, here, up, map.cells.size(), str(map.spawn)])


func _exit_tree() -> void:
	_underground(false)                       # leaving a crypt gives the daylight back


## A CRYPT HAS NO SKY, and the sky is not a property of this scene. A generated world entered
## through a portal is a node added under `scenes/main.tscn`, which keeps its own persistent
## WorldEnvironment and Sun alive throughout — so "outside is pitch black" is not something this
## zone can carry in a file. It has to TAKE the world's look for as long as it is alive and give
## it back afterwards, which is exactly what `DungeonEnv` was written to do for the hand-built
## crypt (`dungeon_generator._dim_world`). This is the same lifecycle around the same call.
##
## It also finds the standalone case for free: `scenes/world/<name>.tscn` writes its own dark
## environment and an unlit sun, and dimming an already dark world is a no-op that restores
## correctly on the way out.
func _underground(dim: bool) -> void:
	var sun := get_tree().get_first_node_in_group("sun") as DirectionalLight3D
	var env_node := get_tree().get_first_node_in_group("world_env")
	var env: Environment = env_node.environment if env_node != null else null
	if dim:
		if not _env_snap.is_empty():          # re-entrancy: never snapshot an already dim world
			return
		var theme: Resource = load(CRYPT_THEME) if ResourceLoader.exists(CRYPT_THEME) else null
		_env_snap = DungeonEnv.apply(env, sun, theme, -1.0, -1.0, _scenery())
	elif not _env_snap.is_empty():
		DungeonEnv.restore(env, sun, _env_snap)
		_env_snap.clear()


## Persistent overworld MESHES that have to go away while an underground zone is alive: blacking
## out the Environment cannot reach geometry, and main.tscn hangs a 700 m CloudSea under the
## world that would otherwise render as a lid of daylit cloud below the crypt's floor. By class,
## for the reason `dungeon_generator` gives: a CloudSea is a CloudSea, and a group would have to
## be remembered by every scene that ever adds one.
func _scenery() -> Array:
	var out: Array = []
	_collect(get_tree().root, out)
	return out


static func _collect(n: Node, out: Array) -> void:
	if n is CloudSea:
		out.append(n)
		return
	for c: Node in n.get_children():
		_collect(c, out)


## ARE THE BUILDINGS THERE? A world's unit scenes are DERIVED — tens of megabytes of baked mesh
## that one command rebuilds — so they are not committed, and a fresh checkout has the map, the
## ground and the manifest but nothing to spawn. Say that once, plainly, with the command that
## fixes it, rather than let the database report every missing scene in turn.
func _units_on_disk() -> bool:
	if map == null or (map.chunks as Array).is_empty():
		return false
	var first := String((map.chunks[0] as Dictionary).get("path", ""))
	if first != "" and ResourceLoader.exists(first):
		return true
	var kind := "city"
	if not (map.zones as Array).is_empty():
		kind = String(((map.zones[0] as Dictionary).brief as Resource).get("kind"))
	push_warning(("[World] %s has its map, its ground and its manifest but none of its %d unit "
			+ "scenes: they are derived and not committed. Rebuild them with
"
			+ "  Godot_console.exe --headless --path . --script res://tools/pa_world.gd -- "
			+ "--kind=%s --seed=%d --name=%s") % [map.name, (map.chunks as Array).size(), kind, map.seed, map.name])
	return false


## The manifest beside this scene, unless one was named. A zone that was never packed (a test
## that built one in memory) has no scene to sit beside and streams nothing, which is correct.
func _manifest() -> String:
	if manifest != "":
		return manifest
	var here := scene_file_path
	if here == "" and owner != null:
		here = owner.scene_file_path
	return here.get_basename() + ".owdb" if here != "" else ""


## The camera the ground should follow: the game's rig if there is one, else the editor's own
## viewport camera so an open world is detailed where you are looking.
func _camera() -> Camera3D:
	var rig: Node = get_tree().get_first_node_in_group("camera_rig")
	if rig != null:
		var cam := rig as Camera3D
		if cam == null:
			var found: Array = rig.find_children("*", "Camera3D", true, false)
			cam = found[0] as Camera3D if not found.is_empty() else null
		if cam != null:
			return cam
	var vp := get_viewport()
	var cur := vp.get_camera_3d() if vp != null else null
	if cur != null:
		return cur
	if Engine.is_editor_hint() and Engine.has_singleton("EditorInterface"):
		var ei: Object = Engine.get_singleton("EditorInterface")
		var evp: Object = ei.call("get_editor_viewport_3d", 0)
		if evp != null:
			return evp.call("get_camera_3d") as Camera3D
	return null


## THE FALLBACK GROUND: one flat body over everything the world covers, for when Terrain3D is
## not installed. Layer 1, the layer the player's floor cast reads.
func _ground() -> void:
	var box: Rect2 = (map.bounds as Rect2).grow(40.0)
	if box.size == Vector2.ZERO:
		box = Rect2(-100, -100, 200, 200)
	var body := StaticBody3D.new()
	body.name = "Ground"
	body.position = Vector3(box.get_center().x, 0.0, box.get_center().y)
	var shape := CollisionShape3D.new()
	var b := BoxShape3D.new()
	b.size = Vector3(box.size.x, 2.0, box.size.y)
	shape.shape = b
	shape.position = Vector3(0.0, -1.0, 0.0)
	body.add_child(shape)
	var mesh := MeshInstance3D.new()
	var plane := PlaneMesh.new()
	plane.size = box.size
	mesh.mesh = plane
	var mat := StandardMaterial3D.new()
	mat.albedo_color = ground_colour
	mat.roughness = 0.95
	mesh.material_override = mat
	body.add_child(mesh)
	add_child(body)
