@tool
extends RefCounted
## Runs through the real enabled EditorPlugin and Godot's scene undo history.
func mouse(plugin: EditorPlugin,camera: Camera3D,point: Vector3,pressed: bool) -> void:
	var event := InputEventMouseButton.new()
	event.button_index=MOUSE_BUTTON_LEFT
	event.pressed=pressed
	event.position=camera.unproject_position(point)
	plugin._forward_3d_gui_input(camera,event)
func run(plugin: EditorPlugin) -> void:
	for i in 90: await plugin.get_tree().process_frame
	var scene := EditorInterface.get_edited_scene_root()
	assert(scene!=null)
	var camera := EditorInterface.get_editor_viewport_3d(0).get_camera_3d()
	camera.global_position=Vector3(16,18,22)
	camera.look_at(Vector3(6,0,0))
	var count: int=plugin._houses(scene).size()
	plugin._set_mode(1)
	mouse(plugin,camera,Vector3(7,0,-2),true)
	var move := InputEventMouseMotion.new()
	move.position=camera.unproject_position(Vector3(12,0,4))
	plugin._forward_3d_gui_input(camera,move)
	mouse(plugin,camera,Vector3(12,0,4),false)
	assert(plugin._houses(scene).size()==count+1,"Rectangle creates one house")
	var house=EditorInterface.get_selection().get_selected_nodes()[0]
	assert(house.owner==scene)
	assert(absf(house.width-5.0)<0.11 and absf(house.depth-6.0)<0.11)
	var history := plugin.get_undo_redo().get_history_undo_redo(plugin.get_undo_redo().get_object_history_id(scene))
	history.undo()
	assert(plugin._houses(scene).size()==count)
	history.redo()
	assert(plugin._houses(scene).size()==count+1)
	print("HOUSE_EDITOR_DRAW_UNDO_REDO_OK")
	plugin._set_mode(2)
	var old_count: int=house.openings.size()
	var place: Vector3=house.to_global(house.wall_point(2,0,1.5,0))
	mouse(plugin,camera,place,true); mouse(plugin,camera,place,false)
	assert(house.openings.size()==old_count+1,"Wall click adds a window")
	history.undo(); assert(house.openings.size()==old_count)
	history.redo(); assert(house.openings.size()==old_count+1)
	print("HOUSE_EDITOR_WINDOW_UNDO_REDO_OK")
	plugin._set_mode(4)
	mouse(plugin,camera,place,true)
	move.position=camera.unproject_position(house.to_global(house.wall_point(2,0.6,1.5,0)))
	plugin._forward_3d_gui_input(camera,move)
	mouse(plugin,camera,house.to_global(house.wall_point(2,0.6,1.5,0)),false)
	assert(float(house.openings[-1].u)>0.1,"Opening follows wall drag")
	history.undo(); assert(absf(float(house.openings[-1].u))<0.01)
	history.redo()
	print("HOUSE_EDITOR_DRAG_UNDO_REDO_OK")
	var gizmo := EditorNode3DGizmo.new()
	gizmo.set_node_3d(house)
	var restore: Dictionary=plugin.gizmos._get_handle_value(gizmo,0,false)
	plugin.gizmos._set_handle(gizmo,0,false,camera,camera.unproject_position(house.to_global(Vector3(3.5,house.wall_height*0.5,0))))
	assert(absf(house.width-7.0)<0.11,"Width handle follows the dragged face")
	plugin.gizmos._commit_handle(gizmo,0,false,restore,false)
	history.undo(); assert(absf(house.width-5.0)<0.11)
	history.redo(); assert(absf(house.width-7.0)<0.11)
	restore=plugin.gizmos._get_handle_value(gizmo,5,false)
	plugin.gizmos._set_handle(gizmo,5,false,camera,camera.unproject_position(house.to_global(Vector3(0,6.2,0))))
	assert(absf(house.wall_height+house.roof_height-6.2)<0.11)
	plugin.gizmos._commit_handle(gizmo,5,false,restore,true)
	assert(house.dimensions()==restore.dimensions)
	print("HOUSE_EDITOR_GIZMO_UNDO_CANCEL_OK")
	plugin._set_mode(0)
	EditorInterface.get_selection().clear()
	EditorInterface.get_selection().add_node(house)
	EditorInterface.edit_node(house)
	plugin._toggle_wing(true)
	assert(house.wing_enabled)
	history.undo(); assert(not house.wing_enabled)
	history.redo(); assert(house.wing_enabled)
	restore=plugin.gizmos._get_handle_value(gizmo,6,false)
	var frame: Transform3D=house.wing_transform()
	var tip: Vector3=frame*Vector3(0,house.wall_height*0.5,(house.width*0.5+house.wing_length)*0.5+1.0)
	plugin.gizmos._set_handle(gizmo,6,false,camera,camera.unproject_position(house.to_global(tip)))
	assert(absf(house.wing_length-float(restore.wing.length)-1.0)<0.11)
	plugin.gizmos._commit_handle(gizmo,6,false,restore,false)
	history.undo(); assert(house.wing_settings()==restore.wing)
	history.redo(); assert(absf(house.wing_length-float(restore.wing.length)-1.0)<0.11)
	restore=plugin.gizmos._get_handle_value(gizmo,7,false)
	frame=house.wing_transform()
	var edge: Vector3=frame*Vector3(2.0,house.wall_height*0.5,(house.width*0.5+house.wing_length)*0.3)
	plugin.gizmos._set_handle(gizmo,7,false,camera,camera.unproject_position(house.to_global(edge)))
	assert(absf(house.wing_width-4.0)<0.11)
	plugin.gizmos._commit_handle(gizmo,7,false,restore,true)
	assert(house.wing_settings()==restore.wing)
	plugin._set_mode(2)
	var wing_point: Vector3=house.to_global(house.wall_point(4,0,1.5))
	camera.global_position=wing_point+house.global_basis*house.wall_normal(4)*12.0+Vector3(0,8,5)
	camera.look_at(wing_point)
	old_count=house.openings.size()
	mouse(plugin,camera,wing_point,true); mouse(plugin,camera,wing_point,false)
	assert(house.openings.size()==old_count+1 and house.openings[-1].wall==4)
	history.undo(); assert(house.openings.size()==old_count)
	history.redo(); assert(house.openings.size()==old_count+1)
	plugin._toggle_wing(false); assert(not house.wing_enabled)
	history.undo(); assert(house.wing_enabled)
	print("HOUSE_EDITOR_WING_ADD_RESIZE_WINDOW_REMOVE_UNDO_OK")
	var opening_index: int=house.openings.size()-1
	var width_handle := 10000+opening_index*2
	restore=plugin.gizmos._get_handle_value(gizmo,width_handle,false)
	var opening: Dictionary=house.resolved_opening(house.openings[opening_index])
	var resize_point: Vector3=house.wall_point(opening.wall,opening.along+0.65,opening.y,0.12)
	plugin.gizmos._set_handle(gizmo,width_handle,false,camera,camera.unproject_position(house.to_global(resize_point)))
	assert(absf(float(house.openings[opening_index].width)-1.3)<0.06)
	plugin.gizmos._commit_handle(gizmo,width_handle,false,restore,false)
	history.undo(); assert(house.openings==restore.openings)
	history.redo(); assert(absf(float(house.openings[opening_index].width)-1.3)<0.06)
	restore=plugin.gizmos._get_handle_value(gizmo,width_handle+1,false)
	resize_point=house.wall_point(opening.wall,opening.along,opening.y+0.7,0.12)
	plugin.gizmos._set_handle(gizmo,width_handle+1,false,camera,camera.unproject_position(house.to_global(resize_point)))
	assert(absf(float(house.openings[opening_index].height)-1.4)<0.06)
	plugin.gizmos._commit_handle(gizmo,width_handle+1,false,restore,true)
	assert(house.openings==restore.openings)
	# Move the resized opening from the wing onto the main rear facade.
	restore=plugin.gizmos._get_handle_value(gizmo,100+opening_index,false)
	var destination: Vector3=house.to_global(house.wall_point(1,0,1.5))
	camera.global_position=destination+house.global_basis*house.wall_normal(1)*12.0+Vector3(2,5,0)
	camera.look_at(destination)
	plugin.gizmos._set_handle(gizmo,100+opening_index,false,camera,camera.unproject_position(destination))
	assert(house.openings[opening_index].wall==1 and house.openings[opening_index].width==1.3)
	plugin.gizmos._commit_handle(gizmo,100+opening_index,false,restore,false)
	history.undo(); assert(house.openings==restore.openings)
	history.redo(); assert(house.openings[opening_index].wall==1)
	print("HOUSE_OPENING_RESIZE_TRANSFER_UNDO_CANCEL_OK")
	# Door height handle grows from the floor, not symmetrically about its center.
	restore=plugin.gizmos._get_handle_value(gizmo,10001,false)
	var door: Dictionary=house.resolved_opening(house.openings[0])
	var door_top: Vector3=house.to_global(house.wall_point(door.wall,door.along,2.2,0.12))
	camera.global_position=door_top+house.global_basis*house.wall_normal(door.wall)*10.0+Vector3(2,3,0)
	camera.look_at(door_top)
	plugin.gizmos._set_handle(gizmo,10001,false,camera,camera.unproject_position(door_top))
	door=house.resolved_opening(house.openings[0])
	assert(absf(door.height-2.2)<0.06 and absf(door.y-door.height*0.5)<0.001)
	plugin.gizmos._commit_handle(gizmo,10001,false,restore,false)
	history.undo(); assert(house.openings==restore.openings)
	history.redo(); assert(absf(float(house.openings[0].height)-2.2)<0.06)
	print("HOUSE_DOOR_RESIZE_FLOOR_ANCHOR_UNDO_OK")
	plugin._plan_action("Interni: crea / mostra")
	var plan=house.get_node("InteriorPlan")
	assert(plan.owner==scene and plan.levels().size()==1)
	plugin._plan_action("Aggiungi muro")
	var authored=EditorInterface.get_selection().get_selected_nodes()[0]
	assert(authored.owner==scene and authored.kind==1)
	var authored_gizmo := EditorNode3DGizmo.new(); authored_gizmo.set_node_3d(authored)
	var old_size: Vector3=authored.dimensions
	plugin.plan_gizmos._set_handle(authored_gizmo,0,false,camera,camera.unproject_position(authored.to_global(Vector3(2,old_size.y*0.5,0))))
	assert(absf(authored.dimensions.x-4.0)<0.06)
	plugin.plan_gizmos._commit_handle(authored_gizmo,0,false,old_size,false)
	history.undo(); assert(authored.dimensions==old_size)
	history.redo(); assert(absf(authored.dimensions.x-4.0)<0.06)
	plugin._plan_action("Aggiungi piano")
	assert(plan.levels().size()==2)
	history.undo(); assert(plan.levels().size()==1)
	history.redo(); assert(plan.levels().size()==2)
	var snapshot: PackedScene=plugin._snapshot(house)
	var copied=snapshot.instantiate()
	assert(copied.get_node("InteriorPlan").levels().size()==2)
	assert(copied.get_node("InteriorPlan").elements()[0].dimensions==authored.dimensions)
	copied.free()
	print("HOUSE_PLAN_EDITOR_GIZMO_UNDO_SNAPSHOT_OK")
	var example=load("res://scenes/dev/house_authoring_example.tscn").instantiate()
	scene.add_child(example); plugin._owned(example,scene)
	var example_plan=example.get_node("InteriorPlan")
	example_plan.organize_furniture()
	EditorInterface.get_selection().clear(); EditorInterface.get_selection().add_node(example)
	var furnished: Array=example_plan.level_records(0)
	plugin._plan_action("Rimuovi arredo generato")
	assert(not example_plan.level_records(0).any(func(r): return r.kind==3))
	history.undo(); assert(example_plan.level_records(0)==furnished)
	history.redo(); assert(not example_plan.level_records(0).any(func(r): return r.kind==3))
	plugin._plan_action("Arreda piano")
	assert(example_plan.level_records(0).any(func(r): return r.kind==3))
	var room_node: Node3D
	for e in example_plan.levels()[0].get_children():
		if e.kind==0 and e.room_type!="ingresso": room_node=e; break
	EditorInterface.get_selection().clear(); EditorInterface.get_selection().add_node(room_node)
	var upper: Array=example_plan.level_records(1)
	plugin._plan_action("Arreda stanza selezionata")
	assert(example_plan.level_records(1)==upper)
	history.undo(); history.redo()
	print("HOUSE_PLAN_FURNISH_EDITOR_SCOPE_UNDO_REDO_OK")
	EditorInterface.get_selection().clear(); EditorInterface.get_selection().add_node(example)
	var version := history.get_version()
	var unchanged: Array=example_plan.level_records(0)
	plugin._plan_action("Integra stanza e genera muri")
	assert(plugin.error_dialog.visible,"Failure dialog must be visible")
	assert("Seleziona il volume" in plugin.error_dialog.dialog_text)
	assert(history.get_version()==version,"Failed proposal added an undo action")
	assert(example_plan.level_records(0)==unchanged)
	plugin.error_dialog.hide()
	print("HOUSE_PLAN_ERROR_DIALOG_NO_UNDO_OK")
	assert(plugin.tabs.get_tab_count()==6)
	EditorInterface.get_selection().clear(); EditorInterface.get_selection().add_node(house); plugin._selection_context()
	plugin.tabs.current_tab=0; assert(plugin.gizmos.focus==house and plugin.gizmos.context==0)
	plugin.tabs.current_tab=1; assert(plugin.gizmos.context==1 and plugin.opening_choice.item_count==house.openings.size())
	plugin._choose_opening(0); assert(plugin.gizmos.active_opening==0)
	EditorInterface.get_selection().clear(); EditorInterface.get_selection().add_node(authored); plugin._selection_context()
	assert(plugin.tabs.current_tab==2 and plugin.plan_gizmos.focus==authored and plugin.gizmos.context==2)
	print("HOUSE_CONTEXT_TABS_FOCUSED_GIZMOS_OK")
	EditorInterface.get_selection().clear(); EditorInterface.get_selection().add_node(house); plugin._selection_context()
	var old_architecture: Dictionary=house.architecture_state(); var old_openings=house.openings.duplicate(true)
	plugin.architecture_choice.select(0); plugin._apply_architecture_profile(true)
	assert(house.architecture_profile.profile_id=="compact_timber" and house.openings==old_openings)
	var profile_history=plugin.get_undo_redo().get_history_undo_redo(plugin.get_undo_redo().get_object_history_id(scene))
	profile_history.undo(); assert(house.architecture_state()==old_architecture)
	profile_history.redo(); assert(house.architecture_profile.profile_id=="compact_timber")
	print("HOUSE_ARCHITECTURE_PROFILE_EDITOR_UNDO_OK")
	var balcony_house=preload("res://addons/house_builder/house.gd").new(); balcony_house.name="BalconyTest"; balcony_house.width=6; balcony_house.wall_height=5.5
	scene.add_child(balcony_house); balcony_house.owner=scene
	plugin._place_balcony({"house":balcony_house,"wall":0,"u":0.0,"y":2.8})
	var balcony=balcony_house.attached_components()[0]; var balcony_id=balcony.component_id
	assert(plugin.tabs.current_tab==4 and plugin.balcony_gizmos.focus==balcony)
	assert(balcony_house.all_openings().size()==1)
	profile_history.undo(); assert(balcony_house.attached_components().is_empty())
	profile_history.redo(); assert(balcony_house.attached_components()[0].component_id==balcony_id)
	EditorInterface.get_selection().clear(); EditorInterface.get_selection().add_node(balcony)
	plugin._remove_balcony(); assert(balcony_house.all_openings().is_empty())
	profile_history.undo(); assert(balcony_house.all_openings().size()==1)
	print("BALCONY_EDITOR_ADD_REMOVE_UNDO_REDO_OK")
	var linked_plan=preload("res://addons/house_builder/plan.gd").new(); linked_plan.name="InteriorPlan"; linked_plan.floor_height=2.8
	balcony_house.add_child(linked_plan); linked_plan.owner=scene
	for i in 2:
		var level := Node3D.new(); level.name="Piano%d"%i; linked_plan.add_child(level); level.owner=scene
	linked_plan.rebuild(); balcony_house.rebuild()
	EditorInterface.get_selection().clear(); EditorInterface.get_selection().add_node(balcony); plugin._selection_context(); plugin._refresh_binding_choices()
	plugin.floor_choice.select(2); plugin._bind_balcony_floor()
	assert(not balcony.floor_id.is_empty()); var linked_floor_id=balcony.floor_id
	profile_history.undo(); assert(balcony.floor_id.is_empty())
	profile_history.redo(); assert(balcony.floor_id==linked_floor_id)
	var access_records: Array[Dictionary]=[{"kind":"door","wall":0,"u":0.1,"floor_y":2.8}]
	balcony_house.openings=access_records
	plugin._refresh_binding_choices(); plugin.door_choice.select(1); plugin._bind_balcony_door()
	assert(not balcony.door_id.is_empty() and balcony.validation_error().is_empty())
	profile_history.undo(); assert(balcony.door_id.is_empty() and not balcony_house.openings[0].has("opening_id"))
	profile_history.redo(); assert(not balcony.door_id.is_empty())
	linked_plan.floor_height=3.1; linked_plan.rebuild(); balcony_house.rebuild()
	assert(is_equal_approx(balcony.position.y,3.1) and is_equal_approx(balcony_house.opening_floor_y(balcony_house.openings[0]),3.1))
	print("BALCONY_EDITOR_FLOOR_MANUAL_DOOR_BIND_UNDO_REDO_OK")
	var old_projection=balcony.projection
	plugin._terrace_selected(true); assert(balcony.exterior_stairs and balcony.support_posts and balcony.projection>=2.4)
	profile_history.undo(); assert(not balcony.exterior_stairs and not balcony.support_posts and balcony.projection==old_projection)
	profile_history.redo(); assert(balcony.exterior_stairs)
	plugin._terrace_selected(false); assert(not balcony.exterior_stairs and balcony.support_posts)
	profile_history.undo(); assert(balcony.exterior_stairs)
	print("TERRACE_EDITOR_CONVERT_REMOVE_STAIR_UNDO_REDO_OK")
	plugin._attach_stair(1); var stair=balcony.stair_component(); assert(stair.side==1 and not balcony.exterior_stairs)
	profile_history.undo(); assert(balcony.stair_component()==null and balcony.exterior_stairs)
	profile_history.redo(); assert(balcony.stair_component()==stair and stair.side==1)
	plugin._attach_stair(2); assert(stair.side==2)
	profile_history.undo(); assert(stair.side==1)
	plugin._delete_stair(); assert(not balcony.has_stairs())
	profile_history.undo(); assert(balcony.stair_component()==stair)
	print("SIDE_STAIRS_EDITOR_ATTACH_SIDE_DELETE_UNDO_OK")
	var fresh_house=preload("res://addons/house_builder/house.gd").new(); fresh_house.name="NewTerraceTest"; fresh_house.width=6; fresh_house.wall_height=5.5
	scene.add_child(fresh_house); fresh_house.owner=scene
	plugin._start_terrace(); plugin._place_balcony({"house":fresh_house,"wall":0,"u":0.0,"y":2.8})
	var fresh_terrace=fresh_house.attached_components()[0]
	assert(fresh_terrace.stair_component()!=null and fresh_terrace.stair_component().owner==scene and not fresh_terrace.exterior_stairs)
	print("NEW_TERRACE_OWNS_INDEPENDENT_STAIR_OK")
	EditorInterface.get_selection().clear(); EditorInterface.get_selection().add_node(fresh_house)
	plugin._add_volume(2); var annex=fresh_house.authored_volumes()[0]; var annex_id=annex.volume_id
	assert(plugin.tabs.current_tab==5 and plugin.gizmos.focus==annex and plugin.gizmos.context==0)
	profile_history.undo(); assert(fresh_house.authored_volumes().is_empty())
	profile_history.redo(); assert(fresh_house.authored_volumes()[0].volume_id==annex_id)
	EditorInterface.get_selection().clear(); EditorInterface.get_selection().add_node(annex)
	plugin._toggle_volume(false); assert(not annex.attached)
	profile_history.undo(); assert(annex.attached)
	plugin._set_volume_junction(1); assert(annex.junction_mode==1)
	profile_history.undo(); assert(annex.junction_mode==0)
	profile_history.redo(); assert(annex.junction_mode==1)
	print("VOLUME_EDITOR_ADD_DETACH_JUNCTION_UNDO_REDO_OK")
	EditorInterface.get_selection().clear(); EditorInterface.get_selection().add_node(fresh_house)
	plugin._add_volume(1,1); var porch=fresh_house.authored_volumes()[1]
	assert(porch.structure_kind==1 and porch.openings.is_empty())
	profile_history.undo(); assert(fresh_house.authored_volumes().size()==1)
	profile_history.redo(); assert(fresh_house.authored_volumes()[1]==porch)
	EditorInterface.get_selection().clear(); EditorInterface.get_selection().add_node(porch)
	plugin._set_canopy_roof(1); assert(porch.canopy_roof==1)
	profile_history.undo(); assert(porch.canopy_roof==0)
	profile_history.redo(); assert(porch.canopy_roof==1)
	print("PORCH_EDITOR_CREATE_ROOF_UNDO_REDO_OK")
	plugin._edit_supports(); var supports=porch.get_node("Supports"); var support_count=supports.get_child_count()
	assert(support_count>0 and supports.get_child(0).owner==scene)
	profile_history.undo(); assert(not porch.has_node("Supports"))
	profile_history.redo(); assert(porch.get_node("Supports")==supports)
	plugin._add_support(); assert(supports.get_child_count()==support_count+1)
	var selected_post=EditorInterface.get_selection().get_selected_nodes()[0]
	assert(plugin.gizmos.context==2 and plugin.support_gizmos.focus==selected_post)
	plugin._remove_support(); assert(supports.get_child_count()==support_count)
	profile_history.undo(); assert(supports.get_child_count()==support_count+1)
	plugin._automatic_supports(); assert(not porch.has_node("Supports"))
	profile_history.undo(); assert(porch.get_node("Supports")==supports)
	print("SUPPORTS_EDITOR_CONVERT_ADD_REMOVE_RESET_UNDO_OK")
	EditorInterface.get_selection().clear(); EditorInterface.get_selection().add_node(supports.get_child(0)); EditorInterface.get_selection().add_node(supports.get_child(1))
	plugin._add_frame_link(); var links=porch.get_node("FrameLinks"); var link=links.get_child(0); var link_id=link.link_id
	assert(plugin.frame_tabs.current_tab==1 and plugin.frame_gizmos.focus==link and plugin.gizmos.context==2)
	profile_history.undo(); assert(not porch.has_node("FrameLinks"))
	profile_history.redo(); assert(porch.get_node("FrameLinks").get_child(0).link_id==link_id)
	EditorInterface.get_selection().clear(); EditorInterface.get_selection().add_node(link)
	plugin._remove_frame_link(); assert(links.get_child_count()==0)
	profile_history.undo(); assert(links.get_child(0)==link)
	print("FRAME_LINK_EDITOR_ADD_REMOVE_UNDO_OK")
	EditorInterface.get_selection().clear(); EditorInterface.get_selection().add_node(house)


	house.update_gizmos()
	for i in 10: await plugin.get_tree().process_frame
	print("HOUSE_GIZMO_NATIVE redraws=",plugin.gizmos.redraw_count," attached=",house.get_gizmos().size())
	assert(plugin.gizmos.redraw_count>0 and not house.get_gizmos().is_empty(),"Native editor must attach and redraw house handles")
	if DisplayServer.get_name()!="headless":
		await RenderingServer.frame_post_draw
		EditorInterface.get_base_control().get_viewport().get_texture().get_image().save_png("res://captures/house_builder/editor.png")
	print("HOUSE_EDITOR_ALL_OK")
	EditorInterface.get_selection().clear()
	EditorInterface.edit_node(scene)
	for i in 2: await plugin.get_tree().process_frame
	plugin.get_tree().quit()
