extends RefCounted
func run(plugin: EditorPlugin) -> void:
 var failures := 0
 var root := EditorInterface.get_edited_scene_root()
 if root==null:
  push_error("No editor scene"); plugin.get_tree().quit(1); return
 var node=root.get_node("AreaConBuco")
 plugin._edit(node)
 var original: Dictionary=node.snapshot()
 plugin._start(false)
 plugin.stroke=PackedVector2Array([Vector2(-6,-5),Vector2(6,-5),Vector2(6,5),Vector2(-6,5)])
 plugin._finish()
 if node.outline.size()!=4 or not node.holes.is_empty(): failures+=1; push_error("Editor check line 13")
 var manager := plugin.get_undo_redo()
 var history := manager.get_history_undo_redo(manager.get_object_history_id(node))
 history.undo(); node.rebuild()
 if node.outline!=original.outline or node.holes!=original.holes: failures+=1; push_error("Editor check line 17")
 history.redo(); node.rebuild()
 if node.outline.size()!=4: failures+=1; push_error("Editor check line 19")
 plugin._start(true)
 plugin.stroke=PackedVector2Array([Vector2(-1,-1),Vector2(1,-1),Vector2(1,1),Vector2(-1,1)])
 plugin._finish(); node.rebuild()
 if node.holes.size()!=1: failures+=1; push_error("Editor check line 23")
 plugin._start(true)
 plugin.stroke=PackedVector2Array([Vector2(20,20),Vector2(21,20),Vector2(21,21)])
 plugin._finish()
 if not plugin.drawing or node.holes.size()!=1: failures+=1; push_error("Editor check line 27")
 plugin._cancel()
 if plugin.drawing: failures+=1; push_error("Editor check line 29")
 var handle := EditorNode3DGizmo.new(); handle.set_node_3d(node)
 var before_handle: Dictionary=node.snapshot()
 node.begin_edit(); node.height+=1; node.rebuild()
 plugin.gizmo._commit_handle(handle,0,false,before_handle,true)
 node.rebuild()
 if node.height!=before_handle.height or node._editing: failures+=1; push_error("Gizmo cancellation")
 node.apply_state(original)
 print("ROCK_OUTCROP_EDITOR failures=",failures)
 plugin.get_tree().quit(1 if failures else 0)
