extends SceneTree
const House=preload("res://addons/house_builder/house.gd")
const Request=preload("res://addons/house_builder/building_request.gd")
func _initialize() -> void: call_deferred("run")
func run() -> void:
	var compact=load("res://addons/house_builder/profiles/compact_timber.tres")
	var nordic=load("res://addons/house_builder/profiles/nordic_longhouse.tres")
	var house := House.new(); root.add_child(house)
	house.depth=7.3; house.openings=[{"kind":"window","wall":0,"u":0.2,"y":1.6}]
	var legacy := house.architecture_state()
	house.apply_architecture(house.architecture_proposal(compact))
	assert(is_equal_approx(house.depth,7.3),"First profile assignment overwrote legacy dimensions")
	house.apply_architecture(house.architecture_proposal(compact,true))
	house.depth=14; var openings=house.openings.duplicate(true)
	house.apply_architecture(house.architecture_proposal(nordic))
	assert(house.depth==14 and house.wall_height==nordic.default_wall_height)
	assert(house.openings==openings and not house.inherited_dimension("depth"))
	var packed := PackedScene.new(); assert(packed.pack(house)==OK)
	assert(ResourceSaver.save(packed,"user://profile_roundtrip.tscn")==OK)
	var copy=load("user://profile_roundtrip.tscn").instantiate()
	assert(copy.depth==14 and copy.architecture_profile.profile_id=="nordic_longhouse")
	copy.apply_architecture(copy.architecture_proposal(compact)); assert(copy.depth==14 and copy.wall_height==4)
	var request := Request.new(); var old_data := request.data(); assert(not old_data.has("schema"))
	request.architecture_profile=nordic; request.archetype_id="hall"
	var generated=request.create_house(); assert(generated.width==request.footprint.x and generated.depth==request.footprint.y)
	assert(generated.archetype_id=="hall" and generated.roof_height==3.2)
	house.apply_architecture(legacy); assert(house.architecture_profile==null and house.authoring_version==1)
	house.free(); copy.free(); generated.free()
	print("ARCHITECTURE_LEGACY_MANUAL_OPENINGS_SAVE_CONTRACT_OK"); quit()
