@tool
extends RefCounted
## Runs through the real enabled EditorPlugin and Godot's scene undo history.
func mouse(plugin: EditorPlugin,camera: Camera3D,point: Vector3,pressed: bool) -> void:
	var event := InputEventMouseButton.new()
	event.button_index=MOUSE_BUTTON_LEFT
	event.pressed=pressed
	event.position=camera.unproject_position(point)
	plugin._forward_3d_gui_input(camera,event)
func run(plugin: EditorPlugin) -> void:
	for i in 90: await plugin.get_tree().process_frame
	var scene := EditorInterface.get_edited_scene_root()
	assert(scene!=null)
	var camera := EditorInterface.get_editor_viewport_3d(0).get_camera_3d()
	camera.global_position=Vector3(16,18,22)
	camera.look_at(Vector3(6,0,0))
	var count: int=plugin._houses(scene).size()
	plugin._set_mode(1)
	mouse(plugin,camera,Vector3(7,0,-2),true)
	var move := InputEventMouseMotion.new()
	move.position=camera.unproject_position(Vector3(12,0,4))
	plugin._forward_3d_gui_input(camera,move)
	mouse(plugin,camera,Vector3(12,0,4),false)
	assert(plugin._houses(scene).size()==count+1,"Rectangle creates one house")
	var house=EditorInterface.get_selection().get_selected_nodes()[0]
	assert(house.owner==scene)
	assert(absf(house.width-5.0)<0.11 and absf(house.depth-6.0)<0.11)
	var history := plugin.get_undo_redo().get_history_undo_redo(plugin.get_undo_redo().get_object_history_id(scene))
	history.undo()
	assert(plugin._houses(scene).size()==count)
	history.redo()
	assert(plugin._houses(scene).size()==count+1)
	print("HOUSE_EDITOR_DRAW_UNDO_REDO_OK")
	plugin._set_mode(2)
	var old_count: int=house.openings.size()
	var place: Vector3=house.to_global(house.wall_point(2,0,1.5,0))
	mouse(plugin,camera,place,true); mouse(plugin,camera,place,false)
	assert(house.openings.size()==old_count+1,"Wall click adds a window")
	history.undo(); assert(house.openings.size()==old_count)
	history.redo(); assert(house.openings.size()==old_count+1)
	print("HOUSE_EDITOR_WINDOW_UNDO_REDO_OK")
	plugin._set_mode(4)
	mouse(plugin,camera,place,true)
	move.position=camera.unproject_position(house.to_global(house.wall_point(2,0.6,1.5,0)))
	plugin._forward_3d_gui_input(camera,move)
	mouse(plugin,camera,house.to_global(house.wall_point(2,0.6,1.5,0)),false)
	assert(float(house.openings[-1].u)>0.1,"Opening follows wall drag")
	history.undo(); assert(absf(float(house.openings[-1].u))<0.01)
	history.redo()
	print("HOUSE_EDITOR_DRAG_UNDO_REDO_OK")
	var gizmo := EditorNode3DGizmo.new()
	gizmo.set_node_3d(house)
	var restore: Dictionary=plugin.gizmos._get_handle_value(gizmo,0,false)
	plugin.gizmos._set_handle(gizmo,0,false,camera,camera.unproject_position(house.to_global(Vector3(3.5,house.wall_height*0.5,0))))
	assert(absf(house.width-7.0)<0.11,"Width handle follows the dragged face")
	plugin.gizmos._commit_handle(gizmo,0,false,restore,false)
	history.undo(); assert(absf(house.width-5.0)<0.11)
	history.redo(); assert(absf(house.width-7.0)<0.11)
	restore=plugin.gizmos._get_handle_value(gizmo,5,false)
	plugin.gizmos._set_handle(gizmo,5,false,camera,camera.unproject_position(house.to_global(Vector3(0,6.2,0))))
	assert(absf(house.wall_height+house.roof_height-6.2)<0.11)
	plugin.gizmos._commit_handle(gizmo,5,false,restore,true)
	assert(house.dimensions()==restore.dimensions)
	print("HOUSE_EDITOR_GIZMO_UNDO_CANCEL_OK")
	plugin._set_mode(0)
	EditorInterface.get_selection().clear()
	EditorInterface.get_selection().add_node(house)
	EditorInterface.edit_node(house)
	plugin._toggle_wing(true)
	assert(house.wing_enabled)
	history.undo(); assert(not house.wing_enabled)
	history.redo(); assert(house.wing_enabled)
	restore=plugin.gizmos._get_handle_value(gizmo,6,false)
	var frame: Transform3D=house.wing_transform()
	var tip: Vector3=frame*Vector3(0,house.wall_height*0.5,(house.width*0.5+house.wing_length)*0.5+1.0)
	plugin.gizmos._set_handle(gizmo,6,false,camera,camera.unproject_position(house.to_global(tip)))
	assert(absf(house.wing_length-float(restore.wing.length)-1.0)<0.11)
	plugin.gizmos._commit_handle(gizmo,6,false,restore,false)
	history.undo(); assert(house.wing_settings()==restore.wing)
	history.redo(); assert(absf(house.wing_length-float(restore.wing.length)-1.0)<0.11)
	restore=plugin.gizmos._get_handle_value(gizmo,7,false)
	frame=house.wing_transform()
	var edge: Vector3=frame*Vector3(2.0,house.wall_height*0.5,(house.width*0.5+house.wing_length)*0.3)
	plugin.gizmos._set_handle(gizmo,7,false,camera,camera.unproject_position(house.to_global(edge)))
	assert(absf(house.wing_width-4.0)<0.11)
	plugin.gizmos._commit_handle(gizmo,7,false,restore,true)
	assert(house.wing_settings()==restore.wing)
	plugin._set_mode(2)
	var wing_point: Vector3=house.to_global(house.wall_point(4,0,1.5))
	camera.global_position=wing_point+house.global_basis*house.wall_normal(4)*12.0+Vector3(0,8,5)
	camera.look_at(wing_point)
	old_count=house.openings.size()
	mouse(plugin,camera,wing_point,true); mouse(plugin,camera,wing_point,false)
	assert(house.openings.size()==old_count+1 and house.openings[-1].wall==4)
	history.undo(); assert(house.openings.size()==old_count)
	history.redo(); assert(house.openings.size()==old_count+1)
	plugin._toggle_wing(false); assert(not house.wing_enabled)
	history.undo(); assert(house.wing_enabled)
	print("HOUSE_EDITOR_WING_ADD_RESIZE_WINDOW_REMOVE_UNDO_OK")
	var opening_index: int=house.openings.size()-1
	var width_handle := 10000+opening_index*2
	restore=plugin.gizmos._get_handle_value(gizmo,width_handle,false)
	var opening: Dictionary=house.resolved_opening(house.openings[opening_index])
	var resize_point: Vector3=house.wall_point(opening.wall,opening.along+0.65,opening.y,0.12)
	plugin.gizmos._set_handle(gizmo,width_handle,false,camera,camera.unproject_position(house.to_global(resize_point)))
	assert(absf(float(house.openings[opening_index].width)-1.3)<0.06)
	plugin.gizmos._commit_handle(gizmo,width_handle,false,restore,false)
	history.undo(); assert(house.openings==restore.openings)
	history.redo(); assert(absf(float(house.openings[opening_index].width)-1.3)<0.06)
	restore=plugin.gizmos._get_handle_value(gizmo,width_handle+1,false)
	resize_point=house.wall_point(opening.wall,opening.along,opening.y+0.7,0.12)
	plugin.gizmos._set_handle(gizmo,width_handle+1,false,camera,camera.unproject_position(house.to_global(resize_point)))
	assert(absf(float(house.openings[opening_index].height)-1.4)<0.06)
	plugin.gizmos._commit_handle(gizmo,width_handle+1,false,restore,true)
	assert(house.openings==restore.openings)
	# Move the resized opening from the wing onto the main rear facade.
	restore=plugin.gizmos._get_handle_value(gizmo,100+opening_index,false)
	var destination: Vector3=house.to_global(house.wall_point(1,0,1.5))
	camera.global_position=destination+house.global_basis*house.wall_normal(1)*12.0+Vector3(2,5,0)
	camera.look_at(destination)
	plugin.gizmos._set_handle(gizmo,100+opening_index,false,camera,camera.unproject_position(destination))
	assert(house.openings[opening_index].wall==1 and house.openings[opening_index].width==1.3)
	plugin.gizmos._commit_handle(gizmo,100+opening_index,false,restore,false)
	history.undo(); assert(house.openings==restore.openings)
	history.redo(); assert(house.openings[opening_index].wall==1)
	print("HOUSE_OPENING_RESIZE_TRANSFER_UNDO_CANCEL_OK")
	# Door height handle grows from the floor, not symmetrically about its center.
	restore=plugin.gizmos._get_handle_value(gizmo,10001,false)
	var door: Dictionary=house.resolved_opening(house.openings[0])
	var door_top: Vector3=house.to_global(house.wall_point(door.wall,door.along,2.2,0.12))
	camera.global_position=door_top+house.global_basis*house.wall_normal(door.wall)*10.0+Vector3(2,3,0)
	camera.look_at(door_top)
	plugin.gizmos._set_handle(gizmo,10001,false,camera,camera.unproject_position(door_top))
	door=house.resolved_opening(house.openings[0])
	assert(absf(door.height-2.2)<0.06 and absf(door.y-door.height*0.5)<0.001)
	plugin.gizmos._commit_handle(gizmo,10001,false,restore,false)
	history.undo(); assert(house.openings==restore.openings)
	history.redo(); assert(absf(float(house.openings[0].height)-2.2)<0.06)
	print("HOUSE_DOOR_RESIZE_FLOOR_ANCHOR_UNDO_OK")
	plugin._plan_action("Interni: crea / mostra")
	var plan=house.get_node("InteriorPlan")
	assert(plan.owner==scene and plan.levels().size()==1)
	plugin._plan_action("Aggiungi muro")
	var authored=EditorInterface.get_selection().get_selected_nodes()[0]
	assert(authored.owner==scene and authored.kind==1)
	var authored_gizmo := EditorNode3DGizmo.new(); authored_gizmo.set_node_3d(authored)
	var old_size: Vector3=authored.dimensions
	plugin.plan_gizmos._set_handle(authored_gizmo,0,false,camera,camera.unproject_position(authored.to_global(Vector3(2,old_size.y*0.5,0))))
	assert(absf(authored.dimensions.x-4.0)<0.06)
	plugin.plan_gizmos._commit_handle(authored_gizmo,0,false,old_size,false)
	history.undo(); assert(authored.dimensions==old_size)
	history.redo(); assert(absf(authored.dimensions.x-4.0)<0.06)
	plugin._plan_action("Aggiungi piano")
	assert(plan.levels().size()==2)
	history.undo(); assert(plan.levels().size()==1)
	history.redo(); assert(plan.levels().size()==2)
	var snapshot: PackedScene=plugin._snapshot(house)
	var copied=snapshot.instantiate()
	assert(copied.get_node("InteriorPlan").levels().size()==2)
	assert(copied.get_node("InteriorPlan").elements()[0].dimensions==authored.dimensions)
	copied.free()
	print("HOUSE_PLAN_EDITOR_GIZMO_UNDO_SNAPSHOT_OK")
	var example=load("res://scenes/dev/house_authoring_example.tscn").instantiate()
	scene.add_child(example); plugin._owned(example,scene)
	var example_plan=example.get_node("InteriorPlan")
	example_plan.organize_furniture()
	EditorInterface.get_selection().clear(); EditorInterface.get_selection().add_node(example)
	var furnished: Array=example_plan.level_records(0)
	plugin._plan_action("Rimuovi arredo generato")
	assert(not example_plan.level_records(0).any(func(r): return r.kind==3))
	history.undo(); assert(example_plan.level_records(0)==furnished)
	history.redo(); assert(not example_plan.level_records(0).any(func(r): return r.kind==3))
	plugin._plan_action("Arreda piano")
	assert(example_plan.level_records(0).any(func(r): return r.kind==3))
	var room_node: Node3D
	for e in example_plan.levels()[0].get_children():
		if e.kind==0 and e.room_type!="ingresso": room_node=e; break
	EditorInterface.get_selection().clear(); EditorInterface.get_selection().add_node(room_node)
	var upper: Array=example_plan.level_records(1)
	plugin._plan_action("Arreda stanza selezionata")
	assert(example_plan.level_records(1)==upper)
	history.undo(); history.redo()
	print("HOUSE_PLAN_FURNISH_EDITOR_SCOPE_UNDO_REDO_OK")
	EditorInterface.get_selection().clear(); EditorInterface.get_selection().add_node(example)
	var version := history.get_version()
	var unchanged: Array=example_plan.level_records(0)
	plugin._plan_action("Integra stanza e genera muri")
	assert(plugin.error_dialog.visible,"Failure dialog must be visible")
	assert("Seleziona il volume" in plugin.error_dialog.dialog_text)
	assert(history.get_version()==version,"Failed proposal added an undo action")
	assert(example_plan.level_records(0)==unchanged)
	plugin.error_dialog.hide()
	print("HOUSE_PLAN_ERROR_DIALOG_NO_UNDO_OK")
	house.update_gizmos()
	for i in 10: await plugin.get_tree().process_frame
	print("HOUSE_GIZMO_NATIVE redraws=",plugin.gizmos.redraw_count," attached=",house.get_gizmos().size())
	assert(plugin.gizmos.redraw_count>0 and not house.get_gizmos().is_empty(),"Native editor must attach and redraw house handles")
	if DisplayServer.get_name()!="headless":
		await RenderingServer.frame_post_draw
		EditorInterface.get_base_control().get_viewport().get_texture().get_image().save_png("res://captures/house_builder/editor.png")
	print("HOUSE_EDITOR_ALL_OK")
	EditorInterface.get_selection().clear()
	EditorInterface.edit_node(scene)
	for i in 2: await plugin.get_tree().process_frame
	plugin.get_tree().quit()
